name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Project Dependencies
        run: pip install '.[test]'

      - name: Debug Installed Packages
        run: pip freeze

      - name: Run flake8
        run: flake8 .

      - name: Run isort
        run: isort --profile=black --check --diff .

      - name: Run black
        run: black --check --diff .
